### ISSUE TITLE
Fails if any invalid semver tags

### ISSUE THREAD

**Issue by rajsite** [practicaljs/github-release-downloader#2]
It would be helpful if the tool had an option to report but ignore invalid semver tags in a repo instead of failing.

**Comment by fazouane-marouane** [comment]
Hi 👋

I'll look into this. Do you have any invalid semver tag in particular? An error message? A repository name that you tried but failed to download due to invalid version ?

**Comment by rajsite** [comment]
For tag examples, the following failed:
1. A tag that is just completely not semver, used for other purposes, `nipkg-feed`
2. A tag that is incorrect semver (and I think fine if ignored), `v1.0.0.1`

**Comment by fazouane-marouane** [comment]
Hello @rajsite 
Thanks for reporting the issue. This has been fixed, as of v1.1.8 😉
Wrong semver versions will be coersed to the closest semver versions (and thus won't be ignored).
