### ISSUE TITLE
Download specific version

### ISSUE THREAD

**Issue by deevus** [practicaljs/github-release-downloader#6]
This looked perfect for my usecase until I discovered `grd` doesn't have an option to download a specific release. 

Would you consider adding it?

Cheers

**Comment by fazouane-marouane** [comment]
Hello @deevus
Sure thing! It most likely just slipped my mind 😄 I'll add it to this week's todo

**Comment by fazouane-marouane** [comment]
@deevus The fix has landed in version 1.1.9 you can look at the read me for more info (a new arg `--match-version`).

**Comment by deevus** [comment]
Thank you :)
